### ISSUE TITLE
Collect import: Report on functions

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1075]
In Collect Import, the system converts all functions to their original datatypes (e.g. text attribute with a function into a plain text attribute). 
In Collect Import Report we should see which are the attributes with functions because these functions need to be created again in Arena.

**Comment by SteRiccio** [comment]
Arena converts attributes marked as "calculated" in Collect as attributes marked as "Read only".
When the expression cannot be converted automatically, the attribute will appear in the import report, and in the type there should be "Default value", with the expression that cannot be converted.
The function defined in Collect must be written in the "Default values" section in the Advanced tab of the node definition editor.
There is no way now to keep the same function in the node def editor, because it is syntactically wrong; it must be copied from the import report and adapted to the new syntax of Arena.
