### ISSUE TITLE
Attribute: Advanced - Applicable if..

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#700]
I was first confused with property "Relevant".
I suggest to change text "Applicable if" to "Relevant if" in order to follow the good old practice familiar to us and already applied in Collect.

In addition, can we get "Hide when not relevant" button similarly as in Collect?

**Comment by minotogna** [comment]
First part will be fixed in #711 

Second part is more tricky.
Hiding fileds based on some condition affect negatively the user experience; plus the position of the elements is statically determined by the user; which means, if a text field becomes hidden, then in the form there will be an empty space

**Comment by laurivesa** [comment]
ok, I can agree with the second part, but could this hiding be an option for the future Mobile app? You do not need to show this checkbox now, but is there ready but as a comment but the system is ready to store it?

**Comment by minotogna** [comment]
Totally, actually on mobile it can be hidden by default.
The mobile is a different story because the screen will include only one variable at the time.
I can close this for now
