### ISSUE TITLE
Expression editor: problem when using Labels

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#701]
In Expression Editor the selected attributes are listed by their labels, not by their names. This causes several problems because we can have for example 
cluster_accessibility -> label: Accessibility
plot_accessibility     -> label: Accessibility

In Collect we used attributes names in XPath expressions. This old Collect system is better, safer and causes less confusion in complex surveys. In addition, Collect Import Report shows you names, not labels!

**Comment by minotogna** [comment]
1. We will use name instead of labels (see #713)

2. You might have missed the advanced editor (that at the moment is available only for DefaultValues) that allows editing the expression manually with ctrl+space auto-complete feature. (see attachment)
![Screen Shot 2020-04-16 at 2 32 37 PM](https://user-images.githubusercontent.com/1138156/79456931-a3308a00-7fef-11ea-9838-aa3e1274de89.png)

Collect Import Report, under Path columns, shows labels not names. The column Expression shows the collect formula, that are not converted in arena format.
